spring:
  datasource:
    url: jdbc:mysql://47.52.72.145:3389/competition_subject?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: ENC(GNTGqKTs2Iu5LCeKJMXiYQ==)
    password: ENC(APtQIanTvhhFZ45wafbNnw==)
    driver-class-name: com.mysql.jdbc.Driver

  # 静态文件
  resources:
    static-locations: classpath:static/
  mvc:
    static-path-pattern: /**


  # redis配置
  redis:
    port: 6388
    password: ENC(qQP6p0t7OegwIl5Ue1mkVg==)
    database: 1
    host: 47.52.72.145
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0  # 连接池中的最小空闲连接
        max-idle: 8
        max-wait: 3000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000

  # rabbitmq
  rabbitmq:
    host: 47.52.72.145
    username: ENC(EUvYvdnpOx8+AIk+rtSkmQ==)
    password: ENC(S4b7L5iuF0T+n5WwLh2+Tg==)
    port: 5670
    virtual-host: ENC(EUvYvdnpOx8+AIk+rtSkmQ==)
    connection-timeout: 60000ms
    # 支持发布确认
    publisher-confirms: true
    # 支持发布返回
    publisher-returns: true


  ## QQ邮箱配置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1748672727@qq.com #发送邮件的邮箱地址
    password: ENC(bJc+7aozRKxhZplatBFOColD3ZIH5SgBfjM0cAXEOSs=) #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    #    properties.mail.smtp.port: 465 #端口号465或587
    from: 1748672727@qq.com # 发送邮件的地址，和上面username一致
    default-encoding: utf-8
    protocol: smtp


#  tomcat:
#    uri-encoding: UTF-8
#    max-threads: 1000
#    min-spare-threads: 30
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true

# swagger.json的访问request mapping路径
springfox:
  documenttation:
    swagger:
      v2:
        path: /api-docs


server:
  port: 8888
  servlet:
    context-path: /subject

mybatis-plus:
  configuration:
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名规则
    map-underscore-to-camel-case: true
    cache-enabled: false

  global-config:
    typeAliasesPackage: com.gxuwz.subject.model
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml


# 全局异常处理：抛出后会被GlobalExceptionHandler.class处理
mvc:
  #出现错误时, 直接抛出异常
  throw-exception-if-no-handler-found: true

jasypt:
  encryptor:
    # 盐
    password: tale666cqf88miracle6TALE_CQF
      #    property:
    # 自定义属性规则，默认前缀是“ENC(”，后缀为“)”
#      prefix: "ENC["
#      suffix: "]"


# 监控服务
management:
  server:
    port: 1688
  endpoint:
    shutdown:
      enabled: true

 # 监控信息
info:
  app:
    name: tale_监控
    url: https://www.jianshu.com/u/7f093d6ed255
    email: ihopyou@qq.com


