server:
  port: 8888
  servlet:
    context-path: /subject

spring:
  datasource:
    url: jdbc:mysql://miraclepeak.xyz:3389/competition_subject?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: ENC(GNTGqKTs2Iu5LCeKJMXiYQ==)
    password: ENC(BS8Z50ImQg3pd0yYonKB5Q==)
#    password: ENC(APtQIanTvhhFZ45wafbNnw==)
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  # 静态文件
  resources:
    static-locations: classpath:static/
  # 映射文件路径
  mvc:
    static-path-pattern: /**

  # json格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  # redis配置
  redis:
    port: 6379
    password: ENC(qQP6p0t7OegwIl5Ue1mkVg==)
    database: 1
    host: 172.17.0.1
    # 连接超时时间
    timeout: 5s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

    # jedis 太low了
#    jedis:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        min-idle: 0  # 连接池中的最小空闲连接
#        max-idle: 8
#        max-wait: 3000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    timeout: 2000

  # rabbitmq
  rabbitmq:
    host: 47.52.72.145
    username: ENC(EUvYvdnpOx8+AIk+rtSkmQ==)
    password: ENC(S4b7L5iuF0T+n5WwLh2+Tg==)
    port: 5670
    virtual-host: ENC(EUvYvdnpOx8+AIk+rtSkmQ==)
    connection-timeout: 60000ms
    # 支持发布确认（开启confirms模式，保证消息可靠性）
    publisher-confirms: true
    # 回调
    publisher-returns: true
    # 开启ACK
    listener:
      direct:
        # 修改确认机制为手动确认，默认为：AUTO：自动确认，auto易导致消息丢失
        # 如： 刚消费到，还没处理，结果进程挂了，比如重启了，那么就尴尬了，
        # RabbitMQ 认为你已经消费了，这数据就丢了。
        # 手动时： 当处理完毕才，才 ack。保证消息的可靠传递还可以开启 RabbitMQ 的持久化
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual


  ## QQ邮箱配置
  mail:
    host: smtp.qq.com # 发送邮件服务器
    username: 1748672727@qq.com # 发送邮件的邮箱地址
    password: ENC(bJc+7aozRKxhZplatBFOColD3ZIH5SgBfjM0cAXEOSs=) #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    #    properties.mail.smtp.port: 465 #端口号465或587
    from: 1748672727@qq.com # 发送邮件的地址，和上面username一致
    default-encoding: utf-8
    protocol: smtp

#  tomcat:
#    uri-encoding: UTF-8
#    max-threads: 1000
#    min-spare-threads: 30
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true

# swagger.json的访问request mapping路径
springfox:
  documenttation:
    swagger:
      v2:
        path: /api-docs


mybatis-plus:
  configuration:
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名规则
    map-underscore-to-camel-case: true
#    cache-enabled: false

  global-config:
    typeAliasesPackage: com.gxuwz.subject.model
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml


# 全局异常处理：抛出后会被GlobalExceptionHandler.class处理
mvc:
  #出现错误时, 直接抛出异常
  throw-exception-if-no-handler-found: true

jasypt:
  encryptor:
    # 盐
    password: tale666cqf88miracle6TALE_CQF
      #    property:
    # 自定义属性规则，默认前缀是“ENC(”，后缀为“)”
#      prefix: "ENC["
#      suffix: "]"


# 监控服务 不指定context则默认/actuator
#management:
#  server:
#    port: 1688
#  endpoint:
#    shutdown:
#      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: 'miracle-prometheus'

 # 监控信息
info:
  app:
    name: tale_监控
    url: 博客地址：https://www.jianshu.com/u/7f093d6ed255
    email: ihopyou@qq.com
# 日志
logging:
  level:
    com.gxuwz.tale: info



